---
- name: Connect to Windows Server using Kerberos
  hosts: all
  gather_facts: false
  connection: winrm
  vars:
    ansible_winrm_transport: kerberos
    ansible_winrm_server_cert_validation: ignore

  tasks:
    - name: Run a simple command on Windows
      ansible.windows.win_command:
        command: whoami











