---
- name: Run PowerShell script on Ubuntu using AWX
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    username_to_check: "targetuser"

  tasks:
    - name: Run PowerShell script using pwsh
      ansible.builtin.shell: |
        pwsh -Command "& {
          param([string]$Username)
          Write-Output 'Checking user: ' + $Username
          # Add your AD query logic here
        } -Username '{{ username_to_check }}'"
      register: pwsh_output

    - name: Show PowerShell output
      debug:
        var: pwsh_output.stdout









