---
- name: Run inline PowerShell script
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Run inline PowerShell
      ansible.windows.win_shell: |
       Write-Output "Hello from AWX!"
       Get-Date



